//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BASEventsTestingUtil.EventDistribution {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventMessage", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Eventing")]
    [System.SerializableAttribute()]
    public partial class EventMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AggregateRootIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AggregateRootTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommitIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrelationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventNamespaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] EventPayLoadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SequenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenantIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AggregateRootID {
            get {
                return this.AggregateRootIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AggregateRootIDField, value) != true)) {
                    this.AggregateRootIDField = value;
                    this.RaisePropertyChanged("AggregateRootID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AggregateRootType {
            get {
                return this.AggregateRootTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AggregateRootTypeField, value) != true)) {
                    this.AggregateRootTypeField = value;
                    this.RaisePropertyChanged("AggregateRootType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CommitID {
            get {
                return this.CommitIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CommitIDField, value) != true)) {
                    this.CommitIDField = value;
                    this.RaisePropertyChanged("CommitID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrelationID {
            get {
                return this.CorrelationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrelationIDField, value) != true)) {
                    this.CorrelationIDField = value;
                    this.RaisePropertyChanged("CorrelationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventNamespace {
            get {
                return this.EventNamespaceField;
            }
            set {
                if ((object.ReferenceEquals(this.EventNamespaceField, value) != true)) {
                    this.EventNamespaceField = value;
                    this.RaisePropertyChanged("EventNamespace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] EventPayLoad {
            get {
                return this.EventPayLoadField;
            }
            set {
                if ((object.ReferenceEquals(this.EventPayLoadField, value) != true)) {
                    this.EventPayLoadField = value;
                    this.RaisePropertyChanged("EventPayLoad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventType {
            get {
                return this.EventTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.EventTypeField, value) != true)) {
                    this.EventTypeField = value;
                    this.RaisePropertyChanged("EventType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName {
            get {
                return this.ModuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleNameField, value) != true)) {
                    this.ModuleNameField = value;
                    this.RaisePropertyChanged("ModuleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SequenceNumber {
            get {
                return this.SequenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SequenceNumberField, value) != true)) {
                    this.SequenceNumberField = value;
                    this.RaisePropertyChanged("SequenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenantID {
            get {
                return this.TenantIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TenantIDField, value) != true)) {
                    this.TenantIDField = value;
                    this.RaisePropertyChanged("TenantID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Version {
            get {
                return this.VersionField;
            }
            set {
                if ((object.ReferenceEquals(this.VersionField, value) != true)) {
                    this.VersionField = value;
                    this.RaisePropertyChanged("Version");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
    [System.SerializableAttribute()]
    public partial class ServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BASEventsTestingUtil.EventDistribution.ServiceException.StatusCodeType ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ErrorMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BASEventsTestingUtil.EventDistribution.ServiceException.StatusCodeType ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException.StatusCodeType", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        public enum StatusCodeType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OK = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CorruptFile = 9000,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unauthorized = 9010,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Duplicate = 9020,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NotFound = 9030,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Stale = 9040,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Error = 9999,
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessValidationException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
    [System.SerializableAttribute()]
    public partial class BusinessValidationException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<BASEventsTestingUtil.EventDistribution.BusinessExceptionMessage> BusinessMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<BASEventsTestingUtil.EventDistribution.BusinessExceptionMessage> BusinessMessages {
            get {
                return this.BusinessMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessMessagesField, value) != true)) {
                    this.BusinessMessagesField = value;
                    this.RaisePropertyChanged("BusinessMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusinessExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
    [System.SerializableAttribute()]
    public partial class BusinessExceptionMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageDefaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BASEventsTestingUtil.EventDistribution.BusinessExceptionMessage.MessageTypes MessageTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageDefault {
            get {
                return this.MessageDefaultField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageDefaultField, value) != true)) {
                    this.MessageDefaultField = value;
                    this.RaisePropertyChanged("MessageDefault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageKey {
            get {
                return this.MessageKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageKeyField, value) != true)) {
                    this.MessageKeyField = value;
                    this.RaisePropertyChanged("MessageKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BASEventsTestingUtil.EventDistribution.BusinessExceptionMessage.MessageTypes MessageType {
            get {
                return this.MessageTypeField;
            }
            set {
                if ((this.MessageTypeField.Equals(value) != true)) {
                    this.MessageTypeField = value;
                    this.RaisePropertyChanged("MessageType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="BusinessExceptionMessage.MessageTypes", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        public enum MessageTypes : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Informational = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Warning = 1,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Error = 2,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="HP.HSP.UA3.Eventing", ConfigurationName="EventDistribution.IEventDistribution")]
    public interface IEventDistribution {
        
        [System.ServiceModel.OperationContractAttribute(Action="HP.HSP.UA3.Eventing/IEventDistribution/ProcessEvent", ReplyAction="HP.HSP.UA3.Eventing/IEventDistribution/ProcessEventResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(BASEventsTestingUtil.EventDistribution.ServiceException), Action="HP.HSP.UA3.Eventing/IEventDistribution/ProcessEventServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        [System.ServiceModel.FaultContractAttribute(typeof(BASEventsTestingUtil.EventDistribution.BusinessValidationException), Action="HP.HSP.UA3.Eventing/IEventDistribution/ProcessEventBusinessValidationExceptionFau" +
            "lt", Name="BusinessValidationException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        void ProcessEvent(BASEventsTestingUtil.EventDistribution.EventMessage @event);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEventDistributionChannel : BASEventsTestingUtil.EventDistribution.IEventDistribution, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EventDistributionClient : System.ServiceModel.ClientBase<BASEventsTestingUtil.EventDistribution.IEventDistribution>, BASEventsTestingUtil.EventDistribution.IEventDistribution {
        
        public EventDistributionClient() {
        }
        
        public EventDistributionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EventDistributionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventDistributionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EventDistributionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ProcessEvent(BASEventsTestingUtil.EventDistribution.EventMessage @event) {
            base.Channel.ProcessEvent(@event);
        }
    }
}
