//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.HSP.UA3.Utilities.LoadTenantDb.MenuService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Command", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenuCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenuItemCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenuItemCommand))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenuCommand))]
    public partial class Command : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.RequestorModel RequestorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ViewTimeStampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.RequestorModel Requestor {
            get {
                return this.RequestorField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestorField, value) != true)) {
                    this.RequestorField = value;
                    this.RaisePropertyChanged("Requestor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ViewTimeStamp {
            get {
                return this.ViewTimeStampField;
            }
            set {
                if ((this.ViewTimeStampField.Equals(value) != true)) {
                    this.ViewTimeStampField = value;
                    this.RaisePropertyChanged("ViewTimeStamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestorModel", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.UserMeta")]
    [System.SerializableAttribute()]
    public partial class RequestorModel : HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.BaseModel {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrowserInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorrelationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.CoreEnumerationsMessagingIdentifierIdType IdentifierIdTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IpAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocaleCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RequestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenantIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrowserInfo {
            get {
                return this.BrowserInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.BrowserInfoField, value) != true)) {
                    this.BrowserInfoField = value;
                    this.RaisePropertyChanged("BrowserInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorrelationId {
            get {
                return this.CorrelationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrelationIdField, value) != true)) {
                    this.CorrelationIdField = value;
                    this.RaisePropertyChanged("CorrelationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentifierId {
            get {
                return this.IdentifierIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierIdField, value) != true)) {
                    this.IdentifierIdField = value;
                    this.RaisePropertyChanged("IdentifierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.CoreEnumerationsMessagingIdentifierIdType IdentifierIdType {
            get {
                return this.IdentifierIdTypeField;
            }
            set {
                if ((this.IdentifierIdTypeField.Equals(value) != true)) {
                    this.IdentifierIdTypeField = value;
                    this.RaisePropertyChanged("IdentifierIdType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress {
            get {
                return this.IpAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IpAddressField, value) != true)) {
                    this.IpAddressField = value;
                    this.RaisePropertyChanged("IpAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocaleCode {
            get {
                return this.LocaleCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocaleCodeField, value) != true)) {
                    this.LocaleCodeField = value;
                    this.RaisePropertyChanged("LocaleCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((this.RequestDateField.Equals(value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenantId {
            get {
                return this.TenantIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TenantIdField, value) != true)) {
                    this.TenantIdField = value;
                    this.RaisePropertyChanged("TenantId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateMenuCommand", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Commands")]
    [System.SerializableAttribute()]
    public partial class UpdateMenuCommand : HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.Command {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenu UpdateMenuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenu UpdateMenu {
            get {
                return this.UpdateMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateMenuField, value) != true)) {
                    this.UpdateMenuField = value;
                    this.RaisePropertyChanged("UpdateMenu");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddMenuItemCommand", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Commands")]
    [System.SerializableAttribute()]
    public partial class AddMenuItemCommand : HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.Command {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenuItem AddMenuItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenuItem AddMenuItem {
            get {
                return this.AddMenuItemField;
            }
            set {
                if ((object.ReferenceEquals(this.AddMenuItemField, value) != true)) {
                    this.AddMenuItemField = value;
                    this.RaisePropertyChanged("AddMenuItem");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateMenuItemCommand", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Commands")]
    [System.SerializableAttribute()]
    public partial class UpdateMenuItemCommand : HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.Command {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenuItem UpdateMenuItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenuItem UpdateMenuItem {
            get {
                return this.UpdateMenuItemField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateMenuItemField, value) != true)) {
                    this.UpdateMenuItemField = value;
                    this.RaisePropertyChanged("UpdateMenuItem");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddMenuCommand", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Commands")]
    [System.SerializableAttribute()]
    public partial class AddMenuCommand : HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.Command {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenu AddMenuField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenu AddMenu {
            get {
                return this.AddMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.AddMenuField, value) != true)) {
                    this.AddMenuField = value;
                    this.RaisePropertyChanged("AddMenu");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddMenu", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Domain")]
    [System.SerializableAttribute()]
    public partial class AddMenu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplaySizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityRightItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenantModuleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplaySize {
            get {
                return this.DisplaySizeField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplaySizeField, value) != true)) {
                    this.DisplaySizeField = value;
                    this.RaisePropertyChanged("DisplaySize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuId {
            get {
                return this.MenuIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuIdField, value) != true)) {
                    this.MenuIdField = value;
                    this.RaisePropertyChanged("MenuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorID {
            get {
                return this.OperatorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorIDField, value) != true)) {
                    this.OperatorIDField = value;
                    this.RaisePropertyChanged("OperatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityRightItemId {
            get {
                return this.SecurityRightItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityRightItemIdField, value) != true)) {
                    this.SecurityRightItemIdField = value;
                    this.RaisePropertyChanged("SecurityRightItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenantModuleId {
            get {
                return this.TenantModuleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TenantModuleIdField, value) != true)) {
                    this.TenantModuleIdField = value;
                    this.RaisePropertyChanged("TenantModuleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseModel", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.UserMeta")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.RequestorModel))]
    public partial class BaseModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CoreEnumerations.Messaging.IdentifierIdType", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.UserMeta")]
    public enum CoreEnumerationsMessagingIdentifierIdType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        System = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateMenu", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Domain")]
    [System.SerializableAttribute()]
    public partial class UpdateMenu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplaySizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityRightItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenantModuleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplaySize {
            get {
                return this.DisplaySizeField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplaySizeField, value) != true)) {
                    this.DisplaySizeField = value;
                    this.RaisePropertyChanged("DisplaySize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuId {
            get {
                return this.MenuIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuIdField, value) != true)) {
                    this.MenuIdField = value;
                    this.RaisePropertyChanged("MenuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorID {
            get {
                return this.OperatorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorIDField, value) != true)) {
                    this.OperatorIDField = value;
                    this.RaisePropertyChanged("OperatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityRightItemId {
            get {
                return this.SecurityRightItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityRightItemIdField, value) != true)) {
                    this.SecurityRightItemIdField = value;
                    this.RaisePropertyChanged("SecurityRightItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenantModuleId {
            get {
                return this.TenantModuleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TenantModuleIdField, value) != true)) {
                    this.TenantModuleIdField = value;
                    this.RaisePropertyChanged("TenantModuleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddMenuItem", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Domain")]
    [System.SerializableAttribute()]
    public partial class AddMenuItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CssClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IocContainterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsVisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ItemLastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelItemKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MitaHelpHtmlContentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleSectionItemKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageHelpHtmlContentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentMenuItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintPreviewContentUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportsContentUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityRightItemIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaseUrl {
            get {
                return this.BaseUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseUrlField, value) != true)) {
                    this.BaseUrlField = value;
                    this.RaisePropertyChanged("BaseUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CssClass {
            get {
                return this.CssClassField;
            }
            set {
                if ((object.ReferenceEquals(this.CssClassField, value) != true)) {
                    this.CssClassField = value;
                    this.RaisePropertyChanged("CssClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultText {
            get {
                return this.DefaultTextField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultTextField, value) != true)) {
                    this.DefaultTextField = value;
                    this.RaisePropertyChanged("DefaultText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IocContainter {
            get {
                return this.IocContainterField;
            }
            set {
                if ((object.ReferenceEquals(this.IocContainterField, value) != true)) {
                    this.IocContainterField = value;
                    this.RaisePropertyChanged("IocContainter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVisible {
            get {
                return this.IsVisibleField;
            }
            set {
                if ((this.IsVisibleField.Equals(value) != true)) {
                    this.IsVisibleField = value;
                    this.RaisePropertyChanged("IsVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ItemLastModified {
            get {
                return this.ItemLastModifiedField;
            }
            set {
                if ((this.ItemLastModifiedField.Equals(value) != true)) {
                    this.ItemLastModifiedField = value;
                    this.RaisePropertyChanged("ItemLastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelItemKey {
            get {
                return this.LabelItemKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelItemKeyField, value) != true)) {
                    this.LabelItemKeyField = value;
                    this.RaisePropertyChanged("LabelItemKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuId {
            get {
                return this.MenuIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuIdField, value) != true)) {
                    this.MenuIdField = value;
                    this.RaisePropertyChanged("MenuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuItemId {
            get {
                return this.MenuItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuItemIdField, value) != true)) {
                    this.MenuItemIdField = value;
                    this.RaisePropertyChanged("MenuItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MitaHelpHtmlContentId {
            get {
                return this.MitaHelpHtmlContentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MitaHelpHtmlContentIdField, value) != true)) {
                    this.MitaHelpHtmlContentIdField = value;
                    this.RaisePropertyChanged("MitaHelpHtmlContentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleSectionItemKey {
            get {
                return this.ModuleSectionItemKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleSectionItemKeyField, value) != true)) {
                    this.ModuleSectionItemKeyField = value;
                    this.RaisePropertyChanged("ModuleSectionItemKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorId {
            get {
                return this.OperatorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorIdField, value) != true)) {
                    this.OperatorIdField = value;
                    this.RaisePropertyChanged("OperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderIndex {
            get {
                return this.OrderIndexField;
            }
            set {
                if ((this.OrderIndexField.Equals(value) != true)) {
                    this.OrderIndexField = value;
                    this.RaisePropertyChanged("OrderIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageHelpHtmlContentId {
            get {
                return this.PageHelpHtmlContentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PageHelpHtmlContentIdField, value) != true)) {
                    this.PageHelpHtmlContentIdField = value;
                    this.RaisePropertyChanged("PageHelpHtmlContentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentMenuItemId {
            get {
                return this.ParentMenuItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentMenuItemIdField, value) != true)) {
                    this.ParentMenuItemIdField = value;
                    this.RaisePropertyChanged("ParentMenuItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrintPreviewContentUrl {
            get {
                return this.PrintPreviewContentUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintPreviewContentUrlField, value) != true)) {
                    this.PrintPreviewContentUrlField = value;
                    this.RaisePropertyChanged("PrintPreviewContentUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportsContentUrl {
            get {
                return this.ReportsContentUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportsContentUrlField, value) != true)) {
                    this.ReportsContentUrlField = value;
                    this.RaisePropertyChanged("ReportsContentUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityRightItemId {
            get {
                return this.SecurityRightItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityRightItemIdField, value) != true)) {
                    this.SecurityRightItemIdField = value;
                    this.RaisePropertyChanged("SecurityRightItemId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateMenuItem", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Domain")]
    [System.SerializableAttribute()]
    public partial class UpdateMenuItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CssClassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefaultTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IocContainterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsVisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ItemLastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelItemKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MitaHelpHtmlContentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleSectionItemKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PageHelpHtmlContentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentMenuItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrintPreviewContentUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportsContentUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecurityRightItemIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaseUrl {
            get {
                return this.BaseUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseUrlField, value) != true)) {
                    this.BaseUrlField = value;
                    this.RaisePropertyChanged("BaseUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CssClass {
            get {
                return this.CssClassField;
            }
            set {
                if ((object.ReferenceEquals(this.CssClassField, value) != true)) {
                    this.CssClassField = value;
                    this.RaisePropertyChanged("CssClass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefaultText {
            get {
                return this.DefaultTextField;
            }
            set {
                if ((object.ReferenceEquals(this.DefaultTextField, value) != true)) {
                    this.DefaultTextField = value;
                    this.RaisePropertyChanged("DefaultText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IocContainter {
            get {
                return this.IocContainterField;
            }
            set {
                if ((object.ReferenceEquals(this.IocContainterField, value) != true)) {
                    this.IocContainterField = value;
                    this.RaisePropertyChanged("IocContainter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVisible {
            get {
                return this.IsVisibleField;
            }
            set {
                if ((this.IsVisibleField.Equals(value) != true)) {
                    this.IsVisibleField = value;
                    this.RaisePropertyChanged("IsVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ItemLastModified {
            get {
                return this.ItemLastModifiedField;
            }
            set {
                if ((this.ItemLastModifiedField.Equals(value) != true)) {
                    this.ItemLastModifiedField = value;
                    this.RaisePropertyChanged("ItemLastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LabelItemKey {
            get {
                return this.LabelItemKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelItemKeyField, value) != true)) {
                    this.LabelItemKeyField = value;
                    this.RaisePropertyChanged("LabelItemKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuId {
            get {
                return this.MenuIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuIdField, value) != true)) {
                    this.MenuIdField = value;
                    this.RaisePropertyChanged("MenuId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuItemId {
            get {
                return this.MenuItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuItemIdField, value) != true)) {
                    this.MenuItemIdField = value;
                    this.RaisePropertyChanged("MenuItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MitaHelpHtmlContentId {
            get {
                return this.MitaHelpHtmlContentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MitaHelpHtmlContentIdField, value) != true)) {
                    this.MitaHelpHtmlContentIdField = value;
                    this.RaisePropertyChanged("MitaHelpHtmlContentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleSectionItemKey {
            get {
                return this.ModuleSectionItemKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleSectionItemKeyField, value) != true)) {
                    this.ModuleSectionItemKeyField = value;
                    this.RaisePropertyChanged("ModuleSectionItemKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorId {
            get {
                return this.OperatorIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorIdField, value) != true)) {
                    this.OperatorIdField = value;
                    this.RaisePropertyChanged("OperatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderIndex {
            get {
                return this.OrderIndexField;
            }
            set {
                if ((this.OrderIndexField.Equals(value) != true)) {
                    this.OrderIndexField = value;
                    this.RaisePropertyChanged("OrderIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PageHelpHtmlContentId {
            get {
                return this.PageHelpHtmlContentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PageHelpHtmlContentIdField, value) != true)) {
                    this.PageHelpHtmlContentIdField = value;
                    this.RaisePropertyChanged("PageHelpHtmlContentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentMenuItemId {
            get {
                return this.ParentMenuItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentMenuItemIdField, value) != true)) {
                    this.ParentMenuItemIdField = value;
                    this.RaisePropertyChanged("ParentMenuItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrintPreviewContentUrl {
            get {
                return this.PrintPreviewContentUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.PrintPreviewContentUrlField, value) != true)) {
                    this.PrintPreviewContentUrlField = value;
                    this.RaisePropertyChanged("PrintPreviewContentUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportsContentUrl {
            get {
                return this.ReportsContentUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportsContentUrlField, value) != true)) {
                    this.ReportsContentUrlField = value;
                    this.RaisePropertyChanged("ReportsContentUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecurityRightItemId {
            get {
                return this.SecurityRightItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityRightItemIdField, value) != true)) {
                    this.SecurityRightItemIdField = value;
                    this.RaisePropertyChanged("SecurityRightItemId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Event", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.TenantConfigurationEvents))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuUpdated))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuItemAdded))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuItemUpdated))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuAdded))]
    public partial class Event : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EventIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EventID {
            get {
                return this.EventIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EventIDField, value) != true)) {
                    this.EventIDField = value;
                    this.RaisePropertyChanged("EventID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelID {
            get {
                return this.ModelIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelIDField, value) != true)) {
                    this.ModelIDField = value;
                    this.RaisePropertyChanged("ModelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelType {
            get {
                return this.ModelTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelTypeField, value) != true)) {
                    this.ModelTypeField = value;
                    this.RaisePropertyChanged("ModelType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TenantConfigurationEvents", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Events")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuUpdated))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuItemAdded))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuItemUpdated))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuAdded))]
    public partial class TenantConfigurationEvents : HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.Event {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuUpdated", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Events")]
    [System.SerializableAttribute()]
    public partial class MenuUpdated : HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.TenantConfigurationEvents {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuId {
            get {
                return this.MenuIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuIdField, value) != true)) {
                    this.MenuIdField = value;
                    this.RaisePropertyChanged("MenuId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItemAdded", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Events")]
    [System.SerializableAttribute()]
    public partial class MenuItemAdded : HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.TenantConfigurationEvents {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuItemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuItemId {
            get {
                return this.MenuItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuItemIdField, value) != true)) {
                    this.MenuItemIdField = value;
                    this.RaisePropertyChanged("MenuItemId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuItemUpdated", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Events")]
    [System.SerializableAttribute()]
    public partial class MenuItemUpdated : HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.TenantConfigurationEvents {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuItemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuItemId {
            get {
                return this.MenuItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuItemIdField, value) != true)) {
                    this.MenuItemIdField = value;
                    this.RaisePropertyChanged("MenuItemId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuAdded", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Events")]
    [System.SerializableAttribute()]
    public partial class MenuAdded : HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.TenantConfigurationEvents {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MenuIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MenuId {
            get {
                return this.MenuIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MenuIdField, value) != true)) {
                    this.MenuIdField = value;
                    this.RaisePropertyChanged("MenuId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
    [System.SerializableAttribute()]
    public partial class ServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.ServiceException.StatusCodeType ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] ErrorMessagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.ServiceException.StatusCodeType ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ErrorMessages {
            get {
                return this.ErrorMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessagesField, value) != true)) {
                    this.ErrorMessagesField = value;
                    this.RaisePropertyChanged("ErrorMessages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException.StatusCodeType", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        public enum StatusCodeType : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            OK = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            CorruptFile = 9000,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Unauthorized = 9010,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Duplicate = 9020,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            NotFound = 9030,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Stale = 9040,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Error = 9999,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenuService.IMenuService")]
    public interface IMenuService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/AddMenu", ReplyAction="http://tempuri.org/IMenuService/AddMenuResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.ServiceException), Action="http://tempuri.org/IMenuService/AddMenuServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuAdded AddMenu(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenuCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/AddMenu", ReplyAction="http://tempuri.org/IMenuService/AddMenuResponse")]
        System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuAdded> AddMenuAsync(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenuCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/UpdateMenu", ReplyAction="http://tempuri.org/IMenuService/UpdateMenuResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.ServiceException), Action="http://tempuri.org/IMenuService/UpdateMenuServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuUpdated UpdateMenu(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenuCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/UpdateMenu", ReplyAction="http://tempuri.org/IMenuService/UpdateMenuResponse")]
        System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuUpdated> UpdateMenuAsync(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenuCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/AddMenuItem", ReplyAction="http://tempuri.org/IMenuService/AddMenuItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.ServiceException), Action="http://tempuri.org/IMenuService/AddMenuItemServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuItemAdded AddMenuItem(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenuItemCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/AddMenuItem", ReplyAction="http://tempuri.org/IMenuService/AddMenuItemResponse")]
        System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuItemAdded> AddMenuItemAsync(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenuItemCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/UpdateMenuItem", ReplyAction="http://tempuri.org/IMenuService/UpdateMenuItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.ServiceException), Action="http://tempuri.org/IMenuService/UpdateMenuItemServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuItemUpdated UpdateMenuItem(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenuItemCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMenuService/UpdateMenuItem", ReplyAction="http://tempuri.org/IMenuService/UpdateMenuItemResponse")]
        System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuItemUpdated> UpdateMenuItemAsync(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenuItemCommand command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMenuServiceChannel : HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.IMenuService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenuServiceClient : System.ServiceModel.ClientBase<HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.IMenuService>, HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.IMenuService {
        
        public MenuServiceClient() {
        }
        
        public MenuServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MenuServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MenuServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuAdded AddMenu(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenuCommand command) {
            return base.Channel.AddMenu(command);
        }
        
        public System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuAdded> AddMenuAsync(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenuCommand command) {
            return base.Channel.AddMenuAsync(command);
        }
        
        public HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuUpdated UpdateMenu(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenuCommand command) {
            return base.Channel.UpdateMenu(command);
        }
        
        public System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuUpdated> UpdateMenuAsync(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenuCommand command) {
            return base.Channel.UpdateMenuAsync(command);
        }
        
        public HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuItemAdded AddMenuItem(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenuItemCommand command) {
            return base.Channel.AddMenuItem(command);
        }
        
        public System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuItemAdded> AddMenuItemAsync(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.AddMenuItemCommand command) {
            return base.Channel.AddMenuItemAsync(command);
        }
        
        public HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuItemUpdated UpdateMenuItem(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenuItemCommand command) {
            return base.Channel.UpdateMenuItem(command);
        }
        
        public System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.MenuItemUpdated> UpdateMenuItemAsync(HP.HSP.UA3.Utilities.LoadTenantDb.MenuService.UpdateMenuItemCommand command) {
            return base.Channel.UpdateMenuItemAsync(command);
        }
    }
}
