//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddAppSettingCommand", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Commands")]
    [System.SerializableAttribute()]
    public partial class AddAppSettingCommand : HP.HSP.UA3.Core.BAS.CQRS.Base.Command, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSetting AppSettingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSetting AppSetting {
            get {
                return this.AppSettingField;
            }
            set {
                if ((object.ReferenceEquals(this.AppSettingField, value) != true)) {
                    this.AppSettingField = value;
                    this.RaisePropertyChanged("AppSetting");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppSetting", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Domain")]
    [System.SerializableAttribute()]
    public partial class AppSetting : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppSettingKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedTSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SettingTypeItemKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenantModuleAppSettingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenantModuleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppSettingKey {
            get {
                return this.AppSettingKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.AppSettingKeyField, value) != true)) {
                    this.AppSettingKeyField = value;
                    this.RaisePropertyChanged("AppSettingKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationIdField, value) != true)) {
                    this.ApplicationIdField = value;
                    this.RaisePropertyChanged("ApplicationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModifiedTS {
            get {
                return this.LastModifiedTSField;
            }
            set {
                if ((this.LastModifiedTSField.Equals(value) != true)) {
                    this.LastModifiedTSField = value;
                    this.RaisePropertyChanged("LastModifiedTS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorID {
            get {
                return this.OperatorIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorIDField, value) != true)) {
                    this.OperatorIDField = value;
                    this.RaisePropertyChanged("OperatorID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettingTypeItemKey {
            get {
                return this.SettingTypeItemKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SettingTypeItemKeyField, value) != true)) {
                    this.SettingTypeItemKeyField = value;
                    this.RaisePropertyChanged("SettingTypeItemKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenantModuleAppSettingId {
            get {
                return this.TenantModuleAppSettingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TenantModuleAppSettingIdField, value) != true)) {
                    this.TenantModuleAppSettingIdField = value;
                    this.RaisePropertyChanged("TenantModuleAppSettingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenantModuleId {
            get {
                return this.TenantModuleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TenantModuleIdField, value) != true)) {
                    this.TenantModuleIdField = value;
                    this.RaisePropertyChanged("TenantModuleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateAppSettingCommand", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Commands")]
    [System.SerializableAttribute()]
    public partial class UpdateAppSettingCommand : HP.HSP.UA3.Core.BAS.CQRS.Base.Command, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSetting AppSettingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSetting AppSetting {
            get {
                return this.AppSettingField;
            }
            set {
                if ((object.ReferenceEquals(this.AppSettingField, value) != true)) {
                    this.AppSettingField = value;
                    this.RaisePropertyChanged("AppSetting");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TenantConfigurationEvents", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Events")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSettingUpdated))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSettingAdded))]
    public partial class TenantConfigurationEvents : HP.HSP.UA3.Core.BAS.CQRS.Base.Event, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppSettingUpdated", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Events")]
    [System.SerializableAttribute()]
    public partial class AppSettingUpdated : HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.TenantConfigurationEvents {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenantModuleAppSettingIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenantModuleAppSettingId {
            get {
                return this.TenantModuleAppSettingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TenantModuleAppSettingIdField, value) != true)) {
                    this.TenantModuleAppSettingIdField = value;
                    this.RaisePropertyChanged("TenantModuleAppSettingId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppSettingAdded", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.TenantConfi" +
        "guration.Contracts.Events")]
    [System.SerializableAttribute()]
    public partial class AppSettingAdded : HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.TenantConfigurationEvents {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenantModuleAppSettingIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenantModuleAppSettingId {
            get {
                return this.TenantModuleAppSettingIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TenantModuleAppSettingIdField, value) != true)) {
                    this.TenantModuleAppSettingIdField = value;
                    this.RaisePropertyChanged("TenantModuleAppSettingId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AppSettingService.IAppSettingService")]
    public interface IAppSettingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppSettingService/AddAppSetting", ReplyAction="http://tempuri.org/IAppSettingService/AddAppSettingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HP.HSP.UA3.Core.BAS.CQRS.Base.ServiceException), Action="http://tempuri.org/IAppSettingService/AddAppSettingServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSettingAdded AddAppSetting(HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AddAppSettingCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppSettingService/AddAppSetting", ReplyAction="http://tempuri.org/IAppSettingService/AddAppSettingResponse")]
        System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSettingAdded> AddAppSettingAsync(HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AddAppSettingCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppSettingService/UpdateAppSetting", ReplyAction="http://tempuri.org/IAppSettingService/UpdateAppSettingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HP.HSP.UA3.Core.BAS.CQRS.Base.ServiceException), Action="http://tempuri.org/IAppSettingService/UpdateAppSettingServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSettingUpdated UpdateAppSetting(HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.UpdateAppSettingCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAppSettingService/UpdateAppSetting", ReplyAction="http://tempuri.org/IAppSettingService/UpdateAppSettingResponse")]
        System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSettingUpdated> UpdateAppSettingAsync(HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.UpdateAppSettingCommand command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAppSettingServiceChannel : HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.IAppSettingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppSettingServiceClient : System.ServiceModel.ClientBase<HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.IAppSettingService>, HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.IAppSettingService {
        
        public AppSettingServiceClient() {
        }
        
        public AppSettingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppSettingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppSettingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppSettingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSettingAdded AddAppSetting(HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AddAppSettingCommand command) {
            return base.Channel.AddAppSetting(command);
        }
        
        public System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSettingAdded> AddAppSettingAsync(HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AddAppSettingCommand command) {
            return base.Channel.AddAppSettingAsync(command);
        }
        
        public HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSettingUpdated UpdateAppSetting(HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.UpdateAppSettingCommand command) {
            return base.Channel.UpdateAppSetting(command);
        }
        
        public System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.AppSettingUpdated> UpdateAppSettingAsync(HP.HSP.UA3.Utilities.LoadTenantDb.AppSettingService.UpdateAppSettingCommand command) {
            return base.Channel.UpdateAppSettingAsync(command);
        }
    }
}
