//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddDataListItemCommand", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Commands")]
    [System.SerializableAttribute()]
    public partial class AddDataListItemCommand : HP.HSP.UA3.Core.BAS.CQRS.Base.Command, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.AddDataListItem AddDataListItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.AddDataListItem AddDataListItem {
            get {
                return this.AddDataListItemField;
            }
            set {
                if ((object.ReferenceEquals(this.AddDataListItemField, value) != true)) {
                    this.AddDataListItemField = value;
                    this.RaisePropertyChanged("AddDataListItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddDataListItem", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Domain")]
    [System.SerializableAttribute()]
    public partial class AddDataListItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListAttributeValue[] DataListAttributeValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemLanguage[] DataListItemLanguagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemLink[] DataListItemLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EffectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ItemIsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ItemLastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListAttributeValue[] DataListAttributeValues {
            get {
                return this.DataListAttributeValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListAttributeValuesField, value) != true)) {
                    this.DataListAttributeValuesField = value;
                    this.RaisePropertyChanged("DataListAttributeValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListId {
            get {
                return this.DataListIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListIdField, value) != true)) {
                    this.DataListIdField = value;
                    this.RaisePropertyChanged("DataListId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListItemId {
            get {
                return this.DataListItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListItemIdField, value) != true)) {
                    this.DataListItemIdField = value;
                    this.RaisePropertyChanged("DataListItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemLanguage[] DataListItemLanguages {
            get {
                return this.DataListItemLanguagesField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListItemLanguagesField, value) != true)) {
                    this.DataListItemLanguagesField = value;
                    this.RaisePropertyChanged("DataListItemLanguages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemLink[] DataListItemLinks {
            get {
                return this.DataListItemLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListItemLinksField, value) != true)) {
                    this.DataListItemLinksField = value;
                    this.RaisePropertyChanged("DataListItemLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffectiveDate {
            get {
                return this.EffectiveDateField;
            }
            set {
                if ((this.EffectiveDateField.Equals(value) != true)) {
                    this.EffectiveDateField = value;
                    this.RaisePropertyChanged("EffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ItemIsActive {
            get {
                return this.ItemIsActiveField;
            }
            set {
                if ((this.ItemIsActiveField.Equals(value) != true)) {
                    this.ItemIsActiveField = value;
                    this.RaisePropertyChanged("ItemIsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ItemLastModified {
            get {
                return this.ItemLastModifiedField;
            }
            set {
                if ((this.ItemLastModifiedField.Equals(value) != true)) {
                    this.ItemLastModifiedField = value;
                    this.RaisePropertyChanged("ItemLastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderIndex {
            get {
                return this.OrderIndexField;
            }
            set {
                if ((this.OrderIndexField.Equals(value) != true)) {
                    this.OrderIndexField = value;
                    this.RaisePropertyChanged("OrderIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDataListItemCommand", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Commands")]
    [System.SerializableAttribute()]
    public partial class UpdateDataListItemCommand : HP.HSP.UA3.Core.BAS.CQRS.Base.Command, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.UpdateDataListItem UpdateDataListItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.UpdateDataListItem UpdateDataListItem {
            get {
                return this.UpdateDataListItemField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateDataListItemField, value) != true)) {
                    this.UpdateDataListItemField = value;
                    this.RaisePropertyChanged("UpdateDataListItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDataListItem", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Domain")]
    [System.SerializableAttribute()]
    public partial class UpdateDataListItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListAttributeValue[] DataListAttributeValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemLanguage[] DataListItemLanguagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemLink[] DataListItemLinksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EffectiveDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ItemIsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ItemLastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListAttributeValue[] DataListAttributeValues {
            get {
                return this.DataListAttributeValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListAttributeValuesField, value) != true)) {
                    this.DataListAttributeValuesField = value;
                    this.RaisePropertyChanged("DataListAttributeValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListId {
            get {
                return this.DataListIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListIdField, value) != true)) {
                    this.DataListIdField = value;
                    this.RaisePropertyChanged("DataListId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListItemId {
            get {
                return this.DataListItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListItemIdField, value) != true)) {
                    this.DataListItemIdField = value;
                    this.RaisePropertyChanged("DataListItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemLanguage[] DataListItemLanguages {
            get {
                return this.DataListItemLanguagesField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListItemLanguagesField, value) != true)) {
                    this.DataListItemLanguagesField = value;
                    this.RaisePropertyChanged("DataListItemLanguages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemLink[] DataListItemLinks {
            get {
                return this.DataListItemLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListItemLinksField, value) != true)) {
                    this.DataListItemLinksField = value;
                    this.RaisePropertyChanged("DataListItemLinks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EffectiveDate {
            get {
                return this.EffectiveDateField;
            }
            set {
                if ((this.EffectiveDateField.Equals(value) != true)) {
                    this.EffectiveDateField = value;
                    this.RaisePropertyChanged("EffectiveDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ItemIsActive {
            get {
                return this.ItemIsActiveField;
            }
            set {
                if ((this.ItemIsActiveField.Equals(value) != true)) {
                    this.ItemIsActiveField = value;
                    this.RaisePropertyChanged("ItemIsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ItemLastModified {
            get {
                return this.ItemLastModifiedField;
            }
            set {
                if ((this.ItemLastModifiedField.Equals(value) != true)) {
                    this.ItemLastModifiedField = value;
                    this.RaisePropertyChanged("ItemLastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderIndex {
            get {
                return this.OrderIndexField;
            }
            set {
                if ((this.OrderIndexField.Equals(value) != true)) {
                    this.OrderIndexField = value;
                    this.RaisePropertyChanged("OrderIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListAttributeValue", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Domain")]
    [System.SerializableAttribute()]
    public partial class DataListAttributeValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListAttributeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListsAttributeValueIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListsItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListsItemValueIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListAttributeId {
            get {
                return this.DataListAttributeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListAttributeIdField, value) != true)) {
                    this.DataListAttributeIdField = value;
                    this.RaisePropertyChanged("DataListAttributeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListsAttributeValueId {
            get {
                return this.DataListsAttributeValueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListsAttributeValueIdField, value) != true)) {
                    this.DataListsAttributeValueIdField = value;
                    this.RaisePropertyChanged("DataListsAttributeValueId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListsItemId {
            get {
                return this.DataListsItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListsItemIdField, value) != true)) {
                    this.DataListsItemIdField = value;
                    this.RaisePropertyChanged("DataListsItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListsItemValueId {
            get {
                return this.DataListsItemValueIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListsItemValueIdField, value) != true)) {
                    this.DataListsItemValueIdField = value;
                    this.RaisePropertyChanged("DataListsItemValueId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListItemLanguage", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Domain")]
    [System.SerializableAttribute()]
    public partial class DataListItemLanguage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LongDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListItemId {
            get {
                return this.DataListItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListItemIdField, value) != true)) {
                    this.DataListItemIdField = value;
                    this.RaisePropertyChanged("DataListItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Local {
            get {
                return this.LocalField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalField, value) != true)) {
                    this.LocalField = value;
                    this.RaisePropertyChanged("Local");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LongDescription {
            get {
                return this.LongDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.LongDescriptionField, value) != true)) {
                    this.LongDescriptionField = value;
                    this.RaisePropertyChanged("LongDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListItemLink", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Domain")]
    [System.SerializableAttribute()]
    public partial class DataListItemLink : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChildIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChildId {
            get {
                return this.ChildIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildIdField, value) != true)) {
                    this.ChildIdField = value;
                    this.RaisePropertyChanged("ChildId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentIdField, value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddDataListCommand", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Commands")]
    [System.SerializableAttribute()]
    public partial class AddDataListCommand : HP.HSP.UA3.Core.BAS.CQRS.Base.Command, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.AddDataList AddDataListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.AddDataList AddDataList {
            get {
                return this.AddDataListField;
            }
            set {
                if ((object.ReferenceEquals(this.AddDataListField, value) != true)) {
                    this.AddDataListField = value;
                    this.RaisePropertyChanged("AddDataList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddDataList", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Domain")]
    [System.SerializableAttribute()]
    public partial class AddDataList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListAttribute[] DataListAttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListsNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenantModuleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentId {
            get {
                return this.ContentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentIdField, value) != true)) {
                    this.ContentIdField = value;
                    this.RaisePropertyChanged("ContentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListAttribute[] DataListAttributes {
            get {
                return this.DataListAttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListAttributesField, value) != true)) {
                    this.DataListAttributesField = value;
                    this.RaisePropertyChanged("DataListAttributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListsName {
            get {
                return this.DataListsNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListsNameField, value) != true)) {
                    this.DataListsNameField = value;
                    this.RaisePropertyChanged("DataListsName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenantModuleId {
            get {
                return this.TenantModuleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TenantModuleIdField, value) != true)) {
                    this.TenantModuleIdField = value;
                    this.RaisePropertyChanged("TenantModuleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListAttribute", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Domain")]
    [System.SerializableAttribute()]
    public partial class DataListAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListsAttributeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastModifiedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeDataListIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeDefaultItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListId {
            get {
                return this.DataListIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListIdField, value) != true)) {
                    this.DataListIdField = value;
                    this.RaisePropertyChanged("DataListId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListsAttributeId {
            get {
                return this.DataListsAttributeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListsAttributeIdField, value) != true)) {
                    this.DataListsAttributeIdField = value;
                    this.RaisePropertyChanged("DataListsAttributeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastModified {
            get {
                return this.LastModifiedField;
            }
            set {
                if ((this.LastModifiedField.Equals(value) != true)) {
                    this.LastModifiedField = value;
                    this.RaisePropertyChanged("LastModified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeDataListId {
            get {
                return this.TypeDataListIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeDataListIdField, value) != true)) {
                    this.TypeDataListIdField = value;
                    this.RaisePropertyChanged("TypeDataListId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeDefaultItemId {
            get {
                return this.TypeDefaultItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeDefaultItemIdField, value) != true)) {
                    this.TypeDefaultItemIdField = value;
                    this.RaisePropertyChanged("TypeDefaultItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDataListCommand", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Commands")]
    [System.SerializableAttribute()]
    public partial class UpdateDataListCommand : HP.HSP.UA3.Core.BAS.CQRS.Base.Command, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.UpdateDataList UpdateDataListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.UpdateDataList UpdateDataList {
            get {
                return this.UpdateDataListField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateDataListField, value) != true)) {
                    this.UpdateDataListField = value;
                    this.RaisePropertyChanged("UpdateDataList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDataList", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Domain")]
    [System.SerializableAttribute()]
    public partial class UpdateDataList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListAttribute[] DataListAttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListsNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TenantModuleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentId {
            get {
                return this.ContentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentIdField, value) != true)) {
                    this.ContentIdField = value;
                    this.RaisePropertyChanged("ContentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListAttribute[] DataListAttributes {
            get {
                return this.DataListAttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListAttributesField, value) != true)) {
                    this.DataListAttributesField = value;
                    this.RaisePropertyChanged("DataListAttributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListsName {
            get {
                return this.DataListsNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListsNameField, value) != true)) {
                    this.DataListsNameField = value;
                    this.RaisePropertyChanged("DataListsName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TenantModuleId {
            get {
                return this.TenantModuleIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TenantModuleIdField, value) != true)) {
                    this.TenantModuleIdField = value;
                    this.RaisePropertyChanged("TenantModuleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListsEvents", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Events")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemUpdated))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsAdded))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsUpdated))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemAdded))]
    public partial class DataListsEvents : HP.HSP.UA3.Core.BAS.CQRS.Base.Event, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListItemUpdated", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Events")]
    [System.SerializableAttribute()]
    public partial class DataListItemUpdated : HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsEvents {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListItemIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListItemId {
            get {
                return this.DataListItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListItemIdField, value) != true)) {
                    this.DataListItemIdField = value;
                    this.RaisePropertyChanged("DataListItemId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListsAdded", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Events")]
    [System.SerializableAttribute()]
    public partial class DataListsAdded : HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsEvents {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DataListAttributeIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DataListAttributeIds {
            get {
                return this.DataListAttributeIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListAttributeIdsField, value) != true)) {
                    this.DataListAttributeIdsField = value;
                    this.RaisePropertyChanged("DataListAttributeIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListId {
            get {
                return this.DataListIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListIdField, value) != true)) {
                    this.DataListIdField = value;
                    this.RaisePropertyChanged("DataListId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListsUpdated", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Events")]
    [System.SerializableAttribute()]
    public partial class DataListsUpdated : HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsEvents {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListId {
            get {
                return this.DataListIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListIdField, value) != true)) {
                    this.DataListIdField = value;
                    this.RaisePropertyChanged("DataListId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataListItemAdded", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Administration.BAS.DataLists.C" +
        "ontracts.Events")]
    [System.SerializableAttribute()]
    public partial class DataListItemAdded : HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsEvents {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DataListAttributeValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataListItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DataListItemLanguagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] DataListItemLinksField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DataListAttributeValues {
            get {
                return this.DataListAttributeValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListAttributeValuesField, value) != true)) {
                    this.DataListAttributeValuesField = value;
                    this.RaisePropertyChanged("DataListAttributeValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataListItemId {
            get {
                return this.DataListItemIdField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListItemIdField, value) != true)) {
                    this.DataListItemIdField = value;
                    this.RaisePropertyChanged("DataListItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DataListItemLanguages {
            get {
                return this.DataListItemLanguagesField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListItemLanguagesField, value) != true)) {
                    this.DataListItemLanguagesField = value;
                    this.RaisePropertyChanged("DataListItemLanguages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] DataListItemLinks {
            get {
                return this.DataListItemLinksField;
            }
            set {
                if ((object.ReferenceEquals(this.DataListItemLinksField, value) != true)) {
                    this.DataListItemLinksField = value;
                    this.RaisePropertyChanged("DataListItemLinks");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="HP.HSP.DataLists", ConfigurationName="DataListsService.IDataListsService")]
    public interface IDataListsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="HP.HSP.DataLists/IDataListsService/AddDataListItem", ReplyAction="HP.HSP.DataLists/IDataListsService/AddDataListItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HP.HSP.UA3.Core.BAS.CQRS.Base.ServiceException), Action="HP.HSP.DataLists/IDataListsService/AddDataListItemServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemAdded AddDataListItem(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.AddDataListItemCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="HP.HSP.DataLists/IDataListsService/AddDataListItem", ReplyAction="HP.HSP.DataLists/IDataListsService/AddDataListItemResponse")]
        System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemAdded> AddDataListItemAsync(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.AddDataListItemCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="HP.HSP.DataLists/IDataListsService/UpdateDataListItem", ReplyAction="HP.HSP.DataLists/IDataListsService/UpdateDataListItemResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HP.HSP.UA3.Core.BAS.CQRS.Base.ServiceException), Action="HP.HSP.DataLists/IDataListsService/UpdateDataListItemServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemUpdated UpdateDataListItem(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.UpdateDataListItemCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="HP.HSP.DataLists/IDataListsService/UpdateDataListItem", ReplyAction="HP.HSP.DataLists/IDataListsService/UpdateDataListItemResponse")]
        System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemUpdated> UpdateDataListItemAsync(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.UpdateDataListItemCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="HP.HSP.DataLists/IDataListsService/AddDataList", ReplyAction="HP.HSP.DataLists/IDataListsService/AddDataListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HP.HSP.UA3.Core.BAS.CQRS.Base.ServiceException), Action="HP.HSP.DataLists/IDataListsService/AddDataListServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsAdded AddDataList(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.AddDataListCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="HP.HSP.DataLists/IDataListsService/AddDataList", ReplyAction="HP.HSP.DataLists/IDataListsService/AddDataListResponse")]
        System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsAdded> AddDataListAsync(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.AddDataListCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="HP.HSP.DataLists/IDataListsService/UpdateDataList", ReplyAction="HP.HSP.DataLists/IDataListsService/UpdateDataListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(HP.HSP.UA3.Core.BAS.CQRS.Base.ServiceException), Action="HP.HSP.DataLists/IDataListsService/UpdateDataListServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/HP.HSP.UA3.Core.BAS.CQRS.Base")]
        HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsUpdated UpdateDataList(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.UpdateDataListCommand command);
        
        [System.ServiceModel.OperationContractAttribute(Action="HP.HSP.DataLists/IDataListsService/UpdateDataList", ReplyAction="HP.HSP.DataLists/IDataListsService/UpdateDataListResponse")]
        System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsUpdated> UpdateDataListAsync(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.UpdateDataListCommand command);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataListsServiceChannel : HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.IDataListsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataListsServiceClient : System.ServiceModel.ClientBase<HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.IDataListsService>, HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.IDataListsService {
        
        public DataListsServiceClient() {
        }
        
        public DataListsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataListsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataListsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataListsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemAdded AddDataListItem(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.AddDataListItemCommand command) {
            return base.Channel.AddDataListItem(command);
        }
        
        public System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemAdded> AddDataListItemAsync(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.AddDataListItemCommand command) {
            return base.Channel.AddDataListItemAsync(command);
        }
        
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemUpdated UpdateDataListItem(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.UpdateDataListItemCommand command) {
            return base.Channel.UpdateDataListItem(command);
        }
        
        public System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListItemUpdated> UpdateDataListItemAsync(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.UpdateDataListItemCommand command) {
            return base.Channel.UpdateDataListItemAsync(command);
        }
        
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsAdded AddDataList(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.AddDataListCommand command) {
            return base.Channel.AddDataList(command);
        }
        
        public System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsAdded> AddDataListAsync(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.AddDataListCommand command) {
            return base.Channel.AddDataListAsync(command);
        }
        
        public HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsUpdated UpdateDataList(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.UpdateDataListCommand command) {
            return base.Channel.UpdateDataList(command);
        }
        
        public System.Threading.Tasks.Task<HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.DataListsUpdated> UpdateDataListAsync(HP.HSP.UA3.Utilities.LoadTenantDb.DataListsService.UpdateDataListCommand command) {
            return base.Channel.UpdateDataListAsync(command);
        }
    }
}
