/****** Object:  Database [AdventureWorks]    ******/
IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'AdventureWorks')
BEGIN
CREATE DATABASE [AdventureWorks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AdventureWorks2016_Data', FILENAME = N'D:\MSSQL\ENV02\Data\AdventureWorks_Data.mdf' , SIZE = 212608KB , MAXSIZE = UNLIMITED, FILEGROWTH = 16384KB )
 LOG ON 
( NAME = N'AdventureWorks2016_Log', FILENAME = N'D:\MSSQL\ENV02\Log\AdventureWorks_Log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 16384KB )
END
GO
ALTER DATABASE [AdventureWorks] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AdventureWorks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AdventureWorks] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AdventureWorks] SET ANSI_NULLS ON 
GO
ALTER DATABASE [AdventureWorks] SET ANSI_PADDING ON 
GO
ALTER DATABASE [AdventureWorks] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [AdventureWorks] SET ARITHABORT ON 
GO
ALTER DATABASE [AdventureWorks] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AdventureWorks] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AdventureWorks] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AdventureWorks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AdventureWorks] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AdventureWorks] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [AdventureWorks] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AdventureWorks] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [AdventureWorks] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AdventureWorks] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AdventureWorks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AdventureWorks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AdventureWorks] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AdventureWorks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AdventureWorks] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AdventureWorks] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AdventureWorks] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AdventureWorks] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AdventureWorks] SET  MULTI_USER 
GO
ALTER DATABASE [AdventureWorks] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AdventureWorks] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AdventureWorks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AdventureWorks] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AdventureWorks] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'AdventureWorks', N'ON'
GO
ALTER DATABASE [AdventureWorks] SET QUERY_STORE = OFF
GO
USE [AdventureWorks]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
IF NOT EXISTS (SELECT * FROM sys.fn_listextendedproperty(N'MS_Description' , NULL,NULL, NULL,NULL, NULL,NULL))
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'AdventureWorks 2016 Sample OLTP Database' 
GO
ALTER DATABASE [AdventureWorks] SET  READ_WRITE 
GO
